config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'dish/0' => 'recipe_pages#sorry'
  get 'fav' => 'recipe_pages#fav'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'
  get 'question_result/question_result'

  post 'menu/question_result' => 'manu_pages#question_result'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  post 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'user_pages/:id/namechange' => 'user_pages#namechange'

  get 'user_pages/:id/newemailinput' => 'user_pages#newemailinput'

  post 'user_pages/:id/emailchange/sentnewmail' => 'user_pages#sentnewmail'

  get 'user_pages/:id/emailchange' => 'user_pages#emailchange', :as => :emailchange

  get 'drawalinput' => 'user_pages#destroyinput'

  post 'drawalconfirm' => 'user_pages#destroyconfirm'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "入力されたメールアドレスへパスワード再設定用のメールを送信しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "入力されたメールアドレスが間違っています。"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password,  "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to user_page_url(@user)
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Beforeフィルタ

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # 正しいユーザーを確認する
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # 再設定用トークンが期限切れかどうかを確認する
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<h1>パスワード再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "メールを送信する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/password_resets/new.html.erb
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<h1>パスワード再設定</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "パスワードを再設定する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>