config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'dish/0' => 'recipe_pages#sorry'
  get 'fav' => 'recipe_pages#fav'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'
  get 'question_result/question_result'

  post 'menu/question_result' => 'manu_pages#question_result'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  post 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'user_pages/:id/namechange' => 'user_pages#namechange'

  get 'user_pages/:id/newemailinput' => 'user_pages#newemailinput'

  post 'user_pages/:id/emailchange/sentnewmail' => 'user_pages#sentnewmail'

  get 'user_pages/:id/emailchange' => 'user_pages#emailchange', :as => :emailchange

  get 'drawalinput' => 'user_pages#destroyinput'

  post 'drawalconfirm' => 'user_pages#destroyconfirm'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/recipe_pages_controller.rb
class RecipePagesController < ApplicationController

  def result

    if session[:maindish].nil? or session[:subdish].nil? or session[:people].nil?
      redirect_to root_path
    else
      if session[:maindish] == 0
        redirect_to action: 'sorry'
      else
        @main = Dish.find(session[:maindish])
        if session[:subdish] != 0
          @sub = Dish.find(session[:subdish])
        else
          @sub = nil
        end
      end
    end
  end

  def recipe
    if session[:maindish].nil? or session[:subdish].nil? or session[:people].nil?
      redirect_to root_path
    else
      @recipe = JSON.parse(Dish.find(params[:id]).recipe)
      @food = JSON.parse(Dish.find(params[:id]).food)
      @favcnt = Dish.find(params[:id])
      if logged_in?
        @user = current_user
      end
    end
  end

  def fav
    @recipe = Dish.find(params[:id])
    @user = current_user
    @user.dishes << @recipe
#    @recipe.users << @user
  end


  def sorry
    if session[:maindish].nil? or session[:subdish].nil? or session[:people].nil?
      redirect_to root_path
    end
  end
end

app/helpers/recipe_pages_helper.rb
module RecipePagesHelper
end

app/views/recipe_pages/fav.html.erb
<h1>「<%= @recipe.dishname %>」をお気に入りに登録しました</h1>
<div>
  <%= link_to 'マイページでお気に入りを確認', user_page_path(current_user) %><br>
  <%= link_to 'レシピへ戻る', :back %><br>
  <%= link_to 'スタート画面へ戻る', root_path %>
</div>

app/views/recipe_pages/recipe.html.erb
<%= stylesheet_link_tag 'frame', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'menu', media: 'all', 'data-turbolinks-track' => true %>
<body>

  <div class="container">
    <!--ヘッダーに関する記述---------------------------------------------------------->
        <%= render 'layouts/header' %>
    <!--ヘッダーに関する記述ここまで---------------------------------------------------->

    <main class="content">
      <section class="contents">
        <article class="grid">
          <p><h3 class="heading">作り方</h3></p>
          <% @recipe.each do |key,value| %>
            <i class="fa fa-lemon-o" aria-hidden="true" style="padding:0px 5px 10px 10px;font-style:bold"></i><%= key.gsub(/step/, "手順") %>
            <p><%= value %></p><br>
          <% end %>

        </article>
        <p class="readmore"><%= link_to "» 戻る", dish_path %></p>

      </section>
    </main>

<!--フッターに関する記述----------------------------------------------------------->
  <%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->
<!--javascriptのファイルの読み込み等-->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

app/views/recipe_pages/result.html.erb
<%= stylesheet_link_tag 'frame', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'menu', media: 'all', 'data-turbolinks-track' => true %>
<body>

  <div class="container">
    <!--ヘッダーに関する記述---------------------------------------------------------->
        <%= render 'layouts/header' %>
    <!--ヘッダーに関する記述ここまで---------------------------------------------------->

  <main class="content">
        <section class="contents">
        <p><h3 class="heading">クッキンマウスくんの献立表</h3></p>
          <!--主菜---------------------------------------------------->
        <article class="grid">
          <h3><%= label_tag 'main',@main.dishname %></h3>
          <% @link = "/recipe/" + @main.id.to_s %>
          <%= image_tag(@main.image,:align => "left") %>
          <div style="padding:10px 0px 10px 10px ; display:box; display:-moz-box; display:-webkit-box;">
            <ul><i class="fa fa-lemon-o" aria-hidden="true" style="padding:0px 5px 10px 10px;font-style:bold"></i>材料
            <% @mainfood = JSON.parse(@main.food) %>
            <% @mainfood.each do |key,value| %>
              <li class="foodlist">
                <% if value[0].to_i > 710 %>
                  <%= Food.find(value[0].to_i-20).fname %>
                <% else %>
                  <%= Food.find(value[0]).fname %>
                <% end %>
                <% value = value[1].to_i %>
             　  <%= value = value * session[:people].to_i %>
                <%= "グラム" %>
              </li>
            <% end %>
          </div>
          <p class="readmore"><%= link_to '» レシピを見る', @link %></p>

        </article>
        <!--主菜ここまで--------------------------------------------->

        <!--副菜---------------------------------------------------->
        <% if not @sub.nil? %>
        <% @sub.each do |key,value| %>
          <article class="grid">
            <h3><%= label_tag 'sub',key.dishname %></h3>
            <% @link = "/recipe/" + key.id.to_s %>
            <%= image_tag(key.image,:align => "left" ) %>
            <div style="padding:10px 0px 10px 10px ; display:box; display:-moz-box; display:-webkit-box;">
              <ul><i class="fa fa-lemon-o" aria-hidden="true" style="padding:0px 5px 10px 10px;font-style:bold"></i>材料
              <% @subfood = JSON.parse(key.food) %>
              <% @subfood.each do |key,value| %>
                <li class="foodlist">
                <% if value[0].to_i > 710 %>
                  <%= Food.find(value[0].to_i-20).fname %>
                <% else %>
                  <%= Food.find(value[0]).fname %>
                <% end %>
                <% value = value[1].to_i %>
             　  <%= value = value * session[:people].to_i %>
                <%= "グラム" %>
              </li>
            <% end %>
          </div>
            <p class="readmore"><%= link_to '» レシピを見る', @link %></p>
          </article>
        <% end %>
        <% end %>
        <!--副菜ここまで--------------------------------------------->
        <p class="readmore"><%= link_to "» 提案をもう一度受ける！", question_path %></p>
      </section>
  </main>

  <!--フッターに関する記述----------------------------------------------------------->
    <%= render 'layouts/footer' %>
  <!--フッターここまで--------------------------------------------------------------->

  </div><!--/.container-->
  <!--javascriptのファイルの読み込み等-->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

app/views/recipe_pages/sorry.html.erb
<%= stylesheet_link_tag 'frame', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'menu', media: 'all', 'data-turbolinks-track' => true %>
<body>

  <div class="container">
    <!--ヘッダーに関する記述---------------------------------------------------------->
        <%= render 'layouts/header' %>
    <!--ヘッダーに関する記述ここまで---------------------------------------------------->

  <main class="content">
        <section class="contents">

        <p><h3 class="heading">クッキンマウスくんの献立表</h3></p>
        <article class="grid">
          <div style="padding:10px 0px 10px 10px ; display:box; display:-moz-box; display:-webkit-box;">
            <p><%= image_tag("mama.png",:align => "left",:size => "160x160") %></p>
            <p><br><br><br><br><br><br><%= "条件に合う献立が見つかりませんでした・・・" %></p>
          </div>
          <p class="readmore"><%= link_to '» もう一度検索する', question_path %></p>

        </article>

      </section>
      <p></p>
  </main>

  <!--フッターに関する記述----------------------------------------------------------->
    <%= render 'layouts/footer' %>
  <!--フッターここまで--------------------------------------------------------------->

  </div><!--/.container-->
  <!--javascriptのファイルの読み込み等-->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>