config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'dish/0' => 'recipe_pages#sorry'
  get 'fav' => 'recipe_pages#fav'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'
  get 'question_result/question_result'

  post 'menu/question_result' => 'manu_pages#question_result'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  post 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'user_pages/:id/namechange' => 'user_pages#namechange'

  get 'user_pages/:id/newemailinput' => 'user_pages#newemailinput'

  post 'user_pages/:id/emailchange/sentnewmail' => 'user_pages#sentnewmail'

  get 'user_pages/:id/emailchange' => 'user_pages#emailchange', :as => :emailchange

  get 'drawalinput' => 'user_pages#destroyinput'

  post 'drawalconfirm' => 'user_pages#destroyconfirm'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/user_pages_controller.rb
class UserPagesController < ApplicationController
  def regist
    @user = User.new
  end

  def profile
    @user = User.find(params[:id])
  end

  def edit
  end

  def login
  end

  def favdeleteselect
    @user = current_user
  end

  def favdelete
    @user = current_user
    favid = params[:fav]
    favid.each do |id|
      @favrecipe = Dish.find(id)
      @user.dishes.destroy(@favrecipe)
    end
    redirect_to :back
  end

  def destroyinput
    @user = current_user
  end

  def destroyconfirm
    @user = current_user
    if @user.authenticate(params[:user][:password])
    else
      flash[:notices] = "入力されたパスワードに誤りがあります"
      redirect_to :back
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end

  def allergies
    @all = Allergy.all
    @user = current_user
  end

  def allergiesinput
    alle = params[:alle]
    @allstr = ""
    if alle.nil?
      @allstr = nil
    else
      alle.each do |all|
        @allstr = @allstr + all.to_s
        if all != alle[-1]
          @allstr = @allstr + ","
        end
      end
    end
    user = current_user
    user.alvalue = @allstr
    user.save
  end

  def namechange
    @user = current_user
  end

  def newemailinput
    @user = current_user
  end

  def emailchange
    @user = User.find(params[:id])
    @user.email = params[:newemail]
  end

  def sentnewmail
    @user = current_user
    @emailadd = user_params[:email]
    same = false
    @userall = User.all
    @userall.each do |userall|
      if @emailadd == userall.email
        same = true
      end
    end
    if @user.email == @emailadd || same
      redirect_to :back
    else
      @user.email = @emailadd
      @user.send_email_change_email
      redirect_to user_page_path(current_user)
      flash[:notices] = "入力されたメールアドレスへメールアドレス再設定メールを送信しました"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      if logged_in?
        redirect_to user_page_path(current_user)
      else
        redirect_to root_path
      end
      flash[:notices] = "ユーザー情報を変更しました"
    else
      redirect_to :back
      flash[:notices] = "変更に失敗しました"
    end
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render 'regist'
    elsif @user.save
      @user.send_activation_email
      flash[:info] = "入力されたメールアドレスにメールを送信しました"
      redirect_to root_url
    else
      render 'regist'
    end
  end

  def confirm
    @user = User.new(user_params)
    render 'regist' if @user.invalid?
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/user_pages/allergies.html.erb
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'allergy-style', media: 'all', 'data-turbolinks-track' => true %>
  <body>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="slide_box">
          <div class="tittle">
            <h2>アレルギー設定</h2>
            <p>アレルギーがあるものを選択してください</p>
          </div>
          <div class="question allergies">
          <%= form_tag 'allergies/allergiesinput' do %>
          <p>
          <% if @user.alvalue != nil %>
            <% checked = @user.alvalue.split(",") %>
          <% end %>
          <% @all.each do |all| %>
            <% if @user.alvalue != nil %>
              <% checkval = checked.include?(all.id.to_s) ? true : false %>
            <% else %>
              <% checkval = false %>
            <% end %>
            <label><p><%= check_box_tag 'alle[]', all.id, checkval, {} %>
            <%= label_tag all.aname  %></p></label>
          <% end %>
          <%= submit_tag "設定する" %></p>
        <% end %>
        </div>
      </div>

</div>

            </section>
          </div><!--/.contents__inner season-resipes-->
        </main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/allergiesinput.html.erb
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">

<div class="row">
  <% if @allstr.nil? %>
    <h1>アレルギー登録なし</h1>
  <% else %>
    <h1>アレルギー登録完了しました</h1>
    <b>登録したアレルギー</b>
    <br>
    <% allname = @allstr.split(",") %>
    <% allname.each do |name| %>
      <% list = Allergy.find(name) %>
      <%= list.aname %><br>
    <% end %>
  <% end %>
  <br>
  <%= link_to 'アレルギー再設定', :back %><br>
  <%= link_to 'マイページ', user_page_path %>
</div>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/confirm.html.erb
<%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">

<h1>確認</h1>

<%= form_for @user, :url => {:controller => "user_pages" } do |f| %>
    名前: <%= @user.name %>
    <%= f.hidden_field :name %>
    <br />
    メールアドレス: <%= @user.email %>
    <%= f.hidden_field :email %>
    <br />
    パスワード: <%= @user.password %>
    <%= f.hidden_field :password %>
    <br />
    <%= f.submit '戻る', name: "back" %>
    <br />
    <%= f.submit '登録'%>
<% end %>


</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/destroyconfirm.html.erb
<%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">

<div class="row">
  <h1>退会</h1>
  <p>楽Laクックを本当に退会しますか？ 退会するとあなたのユーザー情報は削除されます</P>
    <%= link_to (button_tag "退会する"),
        user_page_path(current_user), :method => :delete %>

  <p><%= link_to 'マイページに戻る', user_page_path(current_user) %></p>
</div>
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/destroyinput.html.erb
<%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<div class="row">
  <h1>退会</h1>
  <p>パスワードを入力してください</p>
  <%= form_for @user, :url => drawalconfirm_path, html: {method: "post"} do |f| %>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.submit "退会", class: "btn btn-primary" %>
  <% end %>

</div>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/edit.html.erb
<%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<div class="row">
  <h1>設定</h1>
    <p><%= link_to '» アレルギー', 'allergies' %></p>
    <p><%= link_to '» お気に入りの削除', 'favdeleteselect' %></p>
    <p><%= link_to '» パスワード再設定', new_password_reset_path %></p>
    <p><%= link_to '» ユーザー名変更', 'namechange' %></p>
    <p><%= link_to '» メールアドレス変更', 'newemailinput' %></p>
    <p><%= link_to '» 退会', drawalinput_path %></p>
</dev>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/emailchange.html.erb
<%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">

<div class="row">
  <h1>変更内容確認</h1>
  <p>以下の内容でよろしければ変更ボタンを押してください</p>
  <%= form_for @user, :url => user_page_path, html: {method: "patch"} do |f| %>
    <%= f.label :email, "新しいメールアドレス" %>
    <%= f.email_field :email, class: 'form-control', :readonly => true %>
    <%= f.submit "変更", class: "btn btn-primary" %>
  <% end %>
</div>
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/favdeleteselect.html.erb
      <%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<div class="row">
  <% if @user.dishes.count != 0 %>
    <h1>お気に入りの削除</h1>
    <p>削除したいレシピをチェックして削除ボタンをクリックすることでお気に入りから削除されます</p>
    <%= form_tag 'favdeleteselect/favdelete' do %>
      <% @user.dishes.each do |userfav| %>
        <%= check_box_tag 'fav[]', userfav.id, false, {} %>
        <%= userfav.dishname %><br>
        <% end %>
      <%= submit_tag "削除" %>
      <% end %>
  <% else %>
    <h1>お気に入りレシピはありません</h1>
  <% end %>
  <%= link_to 'マイページ', user_page_path %>
</div>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/login.html.erb
      <%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<h1>UserPages#login</h1>
<p>Find me in app/views/user_pages/login.html.erb</p>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/namechange.html.erb
      <%= stylesheet_link_tag    'profile', media: 'all', "data-turbolinks-track" => true %>
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<div class="row">
  <h1>ユーザー名変更</h1>
  <p>新しいユーザー名を入力してください</p>
  <%= form_for @user, :url => user_page_path, html: {method: "patch"} do |f| %>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.submit "変更", class: "btn btn-primary" %>
  <% end %>
</div>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>

app/views/user_pages/show.html.erb
<%= stylesheet_link_tag 'top-style', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'profile', media: 'all', 'data-turbolinks-track' => true %>


  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container">

<!--ヘッダーに関する記述---------------------------------------------------------->
    <%= render 'layouts/header' %>
<!--ヘッダーに関する記述ここまで---------------------------------------------------->

<!--メインコンテンツに関する記述----------------------------------------------------->
      <main class="contents">
        <div class="contents__inner season-recipes">
          <section>
<div class="row">
  <h1> <%= @user.name %> </h1>
  <% if @user.dishes.count != 0 %>
    <b>お気に入りレシピ</b><br>
    <% @user.dishes.each do |favdish| %>
      <% r_link = 'http://www.rakulacook.com/recipe/' + favdish.id.to_s %>
      <% if favdish.flag == 0
        name = favdish.dishname + "（主菜）"
      else
        name = favdish.dishname + "（副菜）"
      end %>
      <%= link_to name, r_link %>
      <br>
    <% end %>
  <% else %>
      <p>お気に入りレシピはありません</p>
  <% end %>
  <% if @user.alvalue.nil? %>
    <p>アレルギーはありません</p>
  <% else %>
    <br>
    <b>アレルギー</b>
    <br>
    <% alv = @user.alvalue.split(",") %>
    <% alv.each do |alv| %>
      <% an = Allergy.find(alv) %>
      <%= an.aname %>
      <br>
    <% end %>
  <% end %>
  <br>
  <p><%= link_to '» 設定', edit_user_page_path%></p>
</div>

</section>
</div><!--/.contents__inner season-resipes-->
</main>
<!--メインコンテンツに関する記述ここまで---------------------------------------------->

<!--フッターに関する記述----------------------------------------------------------->
<%= render 'layouts/footer' %>
<!--フッターここまで--------------------------------------------------------------->

</div><!--/.container-->

<!--javascriptのファイルの読み込み等-->
<script>
$(document).ready(function(){
$('.bxslider').bxSlider({
mode: 'fade',
speed: 5000,
randomStart: true,
pager: false,
controls: false,
auto: true
});
});
</script>
<script type="text/javascript">
$(document).ready(function(){
if ($(window).width() > 420) {
$('.akineta').bgswitcher({
images: ['/img/top/slide/sample.jpg','/img/top/slide/sample2.jpg','/img/top/slide/sample3.jpg'],
interval: 5000
});
}
});
</script>