config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'dish/0' => 'recipe_pages#sorry'
  get 'fav' => 'recipe_pages#fav'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'
  get 'question_result/question_result'

  post 'menu/question_result' => 'manu_pages#question_result'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  post 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'user_pages/:id/namechange' => 'user_pages#namechange'

  get 'user_pages/:id/newemailinput' => 'user_pages#newemailinput'

  post 'user_pages/:id/emailchange/sentnewmail' => 'user_pages#sentnewmail'

  get 'user_pages/:id/emailchange' => 'user_pages#emailchange', :as => :emailchange

  get 'drawalinput' => 'user_pages#destroyinput'

  post 'drawalconfirm' => 'user_pages#destroyconfirm'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<!--フッターに関する記述----------------------------------------------------------->
<footer class="footer">
        <section>
        <h1><%=link_to root_path do%><%= image_tag '/img/allpage/logo.png', :alt => '楽Laクック' %><% end %></h1>


        <!--アドレス------------------------------------------------------------->
        <address>
          <dl>
            <dt>所在地:</dt>
            <dd>〒733-0013　広島県広島市西区横川新町7-12</dd>
            <dt>電話:</dt>
            <dd><%= link_to '082-291-5050',"tel:0822915050" %></dd>
            <dt>メール</dt>
            <dd><%= link_to 'メールはこちらへ',"mailto:inoue@hsc.ac.jp" %></dd>
          </dl>
        </address>
        <!--アドレスここまで------------------------------------------------------->

        <!--サイトマップ---------------------------------------------------------->
        <ul class="sitemap">
          <li><%= link_to root_path do %><i class="fa fa-chevron-circle-right" aria-hidden="true" ></i>トップ<% end %></li>
          <li><%= link_to "#" do %><i class="fa fa-chevron-circle-right" aria-hidden="true" ></i>献立を探す<% end %></li>
          <li><%= link_to question_path do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>献立提案<% end %></li>
          <% if logged_in? %>
            <li><%= link_to user_page_path(current_user)  do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>マイページ<% end %></li>
            <li><%= link_to logout_path, method: "delete" do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>ログアウト<% end %></li>
          <% else %>
            <li><%= link_to login_path do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>ログイン<% end %></li>
            <li><%= link_to signup_path do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>会員登録<% end %></li>
          <% end %>
          <li><%= link_to "#" do %><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>お問い合わせ<% end %></li>
        </ul>
        <!--サイトマップここまで---------------------------------------------------->

        <p><small>&copy; 2016 楽Laクック | <%= link_to 'Created by Hiroshima Computer College',"http://www.hsc.ac.jp/index.html" %></small></p>
        </section>
</footer>


      <!--フッターここまで--------------------------------------------------------------->

app/views/layouts/_header.html.erb

<header class="header">
  <h1><%=link_to root_path do%><%= image_tag '/img/allpage/logo.png', :alt => '楽Laクック' %><% end %></h1>

  <!--グローバルナビゲーションに関する記述------------------------------------->

  <nav class="gnav sm_hidden">
    <ul>
      <li><%= link_to root_path do %><i class="fa fa-home" title=トップ></i><% end %></li>
      <li><%= link_to "#" do %><i class="fa fa-search" title=献立を探す></i><% end %></li>
      <li><%= link_to question_path  do %><i class="fa fa-file-text-o" title=献立提案></i><% end %></li>
      <li><%= link_to "#" do %><i class="fa fa-line-chart" title=人気の献立></i><% end %></li>
      <li><%= link_to "#" do %><i class="fa fa-envelope" title=お問い合わせ></i><% end %></li>
    </ul>
  </nav>

  <!--グローバルナビゲーションに関する記述ここまで------------------------------->

  <!--ログインボタンや新規登録----------------------------------------------->
  <div class="login">
    <ul>
      <% if logged_in? %>
        <li><%= link_to "マイページ", user_page_path(current_user) %></li>
        <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <li><%= link_to "会員登録", signup_path %></li>
      <% end %>
  </ul>
  </div><!--/.login smhidden-->
  <!--ログインボタンや新規登録ここまで----------------------------------------->

</header>
  <!--<button class="sm_button"><i class="fa fa-bars"></i></button>-->
  <!--スマートフォンの時に表示される横から出スライドしてくるサイドメニューの設定--------------------------------------------------->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 8 ]><html class="no-js ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="no-js ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="no-js ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 8)|!(IE)]><!--><html class="no-js" lang="ja"> <!--<![endif]-->

  <head>
      <meta charset="utf-8">
      <title>今夜の献立に悩んだら／質問に答えるだけ！ 楽Laクック</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">  <!--モバイル端末で閲覧するための設定-->
      <meta name="author" content="ヒロコンの愉快な仲間たち" />  <!--サイトの著者-->
      <meta name="keyword" content="献立,レシピ,ご飯" />        <!--サイトの検索キーワード-->
      <meta name="description" content="広島コンピュータ専門学校の" />    <!--サイトの説明文-->

      <!--ここからCSSファイルの読み込み--------------------------------------------->
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css",:integrity => "sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" , :crossorigin => "anonymous" ,:media => "all" %>
      <!--CSSファイルの読み込みここまで--------------------------------------------->
      <!--javascriptの読み込み-->
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <!--javascriptの読み込み終わり-->
      <%= csrf_meta_tags %>

      <!--ショートカットに表示する画像の設定(ファビコン)-------------------------------->
      <link rel="apple-touch-icon" sizes="180x180" href="img/charcter.png">
      <link rel="icon" href="img/charcter.png" sizes="32x32">
      <link rel="icon" href="img/charcter.png" sizes="16x16">
      <!--ショートカットの画像の設定ここまで------------------------------------------>
  </head>
<%= yield%>

<!-- <%= debug(params) if Rails.env.development? %> -->
</body>
</html>